var annotated_dup =
[
    [ "Gfx", "namespaceGfx.html", [
      [ "CompiledGeometryData", "structGfx_1_1CompiledGeometryData.html", "structGfx_1_1CompiledGeometryData" ],
      [ "EnumArray", "classGfx_1_1EnumArray.html", "classGfx_1_1EnumArray" ],
      [ "FragShaderDefinition", "structGfx_1_1FragShaderDefinition.html", "structGfx_1_1FragShaderDefinition" ],
      [ "FramebufferData", "structGfx_1_1FramebufferData.html", "structGfx_1_1FramebufferData" ],
      [ "ProgramData", "structGfx_1_1ProgramData.html", "structGfx_1_1ProgramData" ],
      [ "ProgramDefinition", "structGfx_1_1ProgramDefinition.html", "structGfx_1_1ProgramDefinition" ],
      [ "Uniforms", "classGfx_1_1Uniforms.html", "classGfx_1_1Uniforms" ],
      [ "VertShaderDefinition", "structGfx_1_1VertShaderDefinition.html", "structGfx_1_1VertShaderDefinition" ]
    ] ],
    [ "magic_enum", "namespacemagic__enum.html", [
      [ "customize", "namespacemagic__enum_1_1customize.html", [
        [ "enum_range< Rml::Input::KeyIdentifier >", "structmagic__enum_1_1customize_1_1enum__range_3_01Rml_1_1Input_1_1KeyIdentifier_01_4.html", "structmagic__enum_1_1customize_1_1enum__range_3_01Rml_1_1Input_1_1KeyIdentifier_01_4" ]
      ] ]
    ] ],
    [ "RendererExtensions", "namespaceRendererExtensions.html", [
      [ "Image", "structRendererExtensions_1_1Image.html", "structRendererExtensions_1_1Image" ]
    ] ],
    [ "AutoCopyEvent", "classAutoCopyEvent.html", "classAutoCopyEvent" ],
    [ "BackendData", "structBackendData.html", "structBackendData" ],
    [ "ClearEvent", "classClearEvent.html", "classClearEvent" ],
    [ "ClipboardAdapter", "classClipboardAdapter.html", "classClipboardAdapter" ],
    [ "ClipboardEvent", "classClipboardEvent.html", "classClipboardEvent" ],
    [ "ClipboardInterface", "classClipboardInterface.html", "classClipboardInterface" ],
    [ "ClipboardListener", "classClipboardListener.html", "classClipboardListener" ],
    [ "ClipboardXX", "classClipboardXX.html", "classClipboardXX" ],
    [ "CompiledFilter", "structCompiledFilter.html", "structCompiledFilter" ],
    [ "CompiledShader", "structCompiledShader.html", "structCompiledShader" ],
    [ "CopyEvent", "classCopyEvent.html", "classCopyEvent" ],
    [ "EditCloseEvent", "classEditCloseEvent.html", "classEditCloseEvent" ],
    [ "EditDoneEvent", "classEditDoneEvent.html", "classEditDoneEvent" ],
    [ "EditEvent", "classEditEvent.html", "classEditEvent" ],
    [ "EditViewModel", "classEditViewModel.html", "classEditViewModel" ],
    [ "ElementClipboard", "classElementClipboard.html", "classElementClipboard" ],
    [ "ElementEdit", "classElementEdit.html", "classElementEdit" ],
    [ "ElementFileManager", "classElementFileManager.html", "classElementFileManager" ],
    [ "ElementShortcuts", "classElementShortcuts.html", "classElementShortcuts" ],
    [ "EventListener", "classEventListener.html", "classEventListener" ],
    [ "EventListenerInstancer", "classEventListenerInstancer.html", "classEventListenerInstancer" ],
    [ "EventManager", "classEventManager.html", "classEventManager" ],
    [ "ExpandEvent", "classExpandEvent.html", "classExpandEvent" ],
    [ "ExportCloseEvent", "classExportCloseEvent.html", "classExportCloseEvent" ],
    [ "ExportEvent", "classExportEvent.html", "classExportEvent" ],
    [ "ExportFileEvent", "classExportFileEvent.html", "classExportFileEvent" ],
    [ "ExportSearchEvent", "classExportSearchEvent.html", "classExportSearchEvent" ],
    [ "FileManager", "classFileManager.html", "classFileManager" ],
    [ "HelpEvent", "classHelpEvent.html", "classHelpEvent" ],
    [ "ImportCloseEvent", "classImportCloseEvent.html", "classImportCloseEvent" ],
    [ "ImportEvent", "classImportEvent.html", "classImportEvent" ],
    [ "ImportFileEvent", "classImportFileEvent.html", "classImportFileEvent" ],
    [ "ImportSearchEvent", "classImportSearchEvent.html", "classImportSearchEvent" ],
    [ "InsertEvent", "classInsertEvent.html", "classInsertEvent" ],
    [ "KeyShortCut", "classKeyShortCut.html", "classKeyShortCut" ],
    [ "KeyShortCutManager", "classKeyShortCutManager.html", "classKeyShortCutManager" ],
    [ "LoadEvent", "classLoadEvent.html", "classLoadEvent" ],
    [ "MemoryCell", "classMemoryCell.html", "classMemoryCell" ],
    [ "MemoryCellManager", "classMemoryCellManager.html", "classMemoryCellManager" ],
    [ "PasteEvent", "classPasteEvent.html", "classPasteEvent" ],
    [ "QObject", "classQObject.html", null ],
    [ "RenderInterface_GL3", "classRenderInterface__GL3.html", "classRenderInterface__GL3" ],
    [ "RenderInterface_GL3_SDL", "classRenderInterface__GL3__SDL.html", "classRenderInterface__GL3__SDL" ],
    [ "ResetShortCutEvent", "classResetShortCutEvent.html", "classResetShortCutEvent" ],
    [ "SearchEvent", "classSearchEvent.html", "classSearchEvent" ],
    [ "ShellFileInterface", "classShellFileInterface.html", "classShellFileInterface" ],
    [ "ShortCutsViewModel", "classShortCutsViewModel.html", "classShortCutsViewModel" ],
    [ "SlotEvent", "classSlotEvent.html", "classSlotEvent" ],
    [ "SystemInterface_SDL", "classSystemInterface__SDL.html", "classSystemInterface__SDL" ],
    [ "TGAHeader", "structTGAHeader.html", "structTGAHeader" ],
    [ "TranslationManager", "classTranslationManager.html", "classTranslationManager" ],
    [ "WindowFocusEvent", "classWindowFocusEvent.html", "classWindowFocusEvent" ]
];